#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

alias original_parent="git rev-parse --abbrev-ref --symbolic-full-name @{u} 2>/dev/null"
alias main_parent="git merge-base HEAD main 2>/dev/null"

head=$(original_parent || main_parent || echo "HEAD")

npx --no -- commitlint --from=$head --to=HEAD
